### ISSUE TITLE
Establish root of Trust

### ISSUE THREAD

**Issue by ErikLundJensen** [DelineaXPM/dsv-k8s-sidecar#47]
I have a few questions to this new sidecar/controller solution.

1) How does the sidecar authenticate towards the controller? If none, do we then have to rely only on network policies to restrict access?

2) How do we prevent the controller's client secret to be copied and used in other contexts? Having the "golden" keys as secrets in Kubernetes does not make the solution more secure than having the real secrets as plain Kubernetes secrets as I see it. 
Other products in the market does a callback to the Kubernetes cluster to verify that the client actually is a running container in a particular cluster & namespace. Does Secret Server have other means for establishing root of trust?

**Comment by sheldonhull** [comment]
@ErikLundJensen for the authentication towards controller, did you see the diagram on the JWT token in the [architecture docs](https://github.com/DelineaXPM/dsv-k8s-sidecar/blob/main/docs/architecture.md)? Take a peek at that.

The second item mentions Secret server, so to be clear, you understand this repo is specifically for DevOps Secrets Vault, not Secret Server sidecar integration right? Just making sure you are in the right place :grin: as that's been mixed up a few times.

**Comment by ErikLundJensen** [comment]
Thanks for the clarification (and also for clarifying my mix up of the two products).

My second question could also be asked for the DevOps Secrets Vault.
How does the controller authenticate towards DSV and thereby establish root of trust?

**Comment by sheldonhull** [comment]
> Thanks for the clarification (and also for clarifying my mix up of the two products).
> 
> My second question could also be asked for the DevOps Secrets Vault. How does the controller authenticate towards DSV and thereby establish root of trust?

Did the architecture diagram not explain?

**Comment by ErikLundJensen** [comment]
The diagram shows an authentication towards DSV. There is no call-back from DSV to Kubernetes to verify that the request is actually coming from a trusted source.
In the old classic world of virtual machine and bare metal machines the root of trust was typical gain during the install process of private keys and certificates at the server. However, in a containerized world these processes do not work as the container can run at many different servers.
In Kubernetes the root of trust can be gained for example by having the DSVControllerPod to forward the Kubernetes JWT token to DSV which then could verify the token by a callback to the Kubernetes TokenReview API.
Thereby DVS could ensure that the request is actually coming from a known Kubernetes cluster and from a pod within a known namespace.
